"""
Markdown + LaTeX renderer.

Takes a list of computation steps and produces a research note.
"""
import json
import sys
import time
from pathlib import Path

PROJECT_ROOT = Path(__file__).parent.parent.parent
OUTPUT_DIR = PROJECT_ROOT / "research_notes"


def render_research_note(
    title: str,
    problem: str,
    steps: list,
    scripts: list = None,
) -> str:
    """Render a complete research note in Markdown.

    Args:
        title: Note title.
        problem: Problem statement.
        steps: List of dicts with keys: name, description, result, latex.
        scripts: Optional list of Python script strings.

    Returns:
        Markdown string.
    """
    lines = []
    lines.append(f"# {title}")
    lines.append("")
    lines.append("## Problem Statement")
    lines.append("")
    lines.append(problem)
    lines.append("")

    for i, step in enumerate(steps, 1):
        name = step.get("name", f"Step {i}")
        lines.append(f"## Step {i}: {name}")
        lines.append("")
        if step.get("description"):
            lines.append(step["description"])
            lines.append("")
        if step.get("latex"):
            lines.append("$$")
            lines.append(step["latex"])
            lines.append("$$")
            lines.append("")

    # Final result (last step)
    if steps:
        last = steps[-1]
        lines.append("## Final Result")
        lines.append("")
        if last.get("latex"):
            lines.append("$$")
            lines.append(last["latex"])
            lines.append("$$")
            lines.append("")

    # Verification section
    verification_steps = [s for s in steps if s.get("verified") is not None]
    if verification_steps:
        lines.append("## Verification")
        lines.append("")
        for vs in verification_steps:
            status = "Verified" if vs.get("verified") else "FAILED"
            lines.append(f"- **{vs.get('name', 'Check')}**: {status}")
            if vs.get("verification_detail"):
                lines.append(f"  - {vs['verification_detail']}")
        lines.append("")

    # Scripts section
    if scripts:
        lines.append("## Scripts")
        lines.append("")
        for i, script in enumerate(scripts, 1):
            lines.append(f"<details>")
            lines.append(f"<summary>Script {i}</summary>")
            lines.append("")
            lines.append("```python")
            lines.append(script)
            lines.append("```")
            lines.append("")
            lines.append("</details>")
            lines.append("")

    lines.append("---")
    lines.append(f"*Generated by Math IDE*")
    lines.append("")

    return "\n".join(lines)


def save_note(content: str, filename: str = None) -> str:
    """Save a research note to disk.

    Returns the file path.
    """
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    if not filename:
        timestamp = time.strftime("%Y%m%d_%H%M%S")
        filename = f"note_{timestamp}.md"
    if not filename.endswith(".md"):
        filename += ".md"

    path = OUTPUT_DIR / filename
    path.write_text(content, encoding="utf-8")
    return str(path)


if __name__ == "__main__":
    # CLI: reads JSON from stdin with title, problem, steps
    data = json.loads(sys.stdin.read())
    md = render_research_note(
        title=data.get("title", "Untitled"),
        problem=data.get("problem", ""),
        steps=data.get("steps", []),
        scripts=data.get("scripts"),
    )
    filename = data.get("filename")
    path = save_note(md, filename)
    print(json.dumps({"path": path, "content": md, "success": True}))
